# Generated by Django 5.1.2 on 2024-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="имя"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="отчество"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="фамилия"
            ),
        ),
    ]
