# Generated by Django 5.1.2 on 2024-10-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_name_user_patronymic_user_surname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
    ]
