# Generated by Django 5.1.2 on 2024-10-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название текста"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание компании. Основной текст",
                    ),
                ),
                (
                    "history",
                    models.TextField(blank=True, null=True, verbose_name="История"),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True, null=True, verbose_name="Миссия и ценности"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="фамилия"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="имя"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="отчество"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="addinfo/avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер телефона",
                        max_length=15,
                        null=True,
                        verbose_name="phone",
                    ),
                ),
                (
                    "adress",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "map",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="addinfo/maps/",
                        verbose_name="Карта",
                    ),
                ),
                (
                    "mapurl",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на карту"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Адрес эл. почты",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Действующая информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные о компании",
                "verbose_name_plural": "Данные о компании",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Тема обращения",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ваше обращение"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ваша фамилия",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ваше имя"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер телефона",
                        max_length=15,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Адрес эл. почты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма обратной связи",
                "verbose_name_plural": "Формы обратной связи",
            },
        ),
    ]
