# Generated by Django 5.1.2 on 2024-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comtext",
            options={
                "verbose_name": "Данные о компании",
                "verbose_name_plural": "Данные о компании",
            },
        ),
        migrations.AddField(
            model_name="comtext",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="имя"
            ),
        ),
        migrations.AlterField(
            model_name="comtext",
            name="name",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Название текста"
            ),
            preserve_default=False,
        ),
    ]
