# Generated by Django 5.1.2 on 2024-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addinfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="feedback",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ваше обращение"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Новая"),
                    ("InProgress", "В работе"),
                    ("Complete", "Заверешена"),
                ],
                default="Новая",
                verbose_name="Статус",
            ),
        ),
    ]
