# Generated by Django 5.1.2 on 2024-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addinfo", "0002_alter_comtext_options_comtext_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comtext",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Действующая информация"
            ),
        ),
        migrations.AddField(
            model_name="comtext",
            name="map",
            field=models.ImageField(
                blank=True, null=True, upload_to="addinfo/maps/", verbose_name="Карта"
            ),
        ),
        migrations.AddField(
            model_name="comtext",
            name="mapurl",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на карту"
            ),
        ),
        migrations.AlterField(
            model_name="comtext",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Адрес эл. почты"
            ),
        ),
    ]
