# Generated by Django 5.1.2 on 2024-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addinfo", "0002_feedback_feedback_feedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="comtext",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Основная информация"
            ),
        ),
    ]
