# Generated by Django 5.1.2 on 2024-10-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Направление медицыны"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Направление медицыны"
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление медицыны",
                "verbose_name_plural": "Направления медицыны",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100, verbose_name="фамилия")),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="отчество"
                    ),
                ),
                (
                    "biography",
                    models.TextField(blank=True, null=True, verbose_name="биография"),
                ),
                (
                    "appointments",
                    models.TextField(
                        blank=True, null=True, verbose_name="записи на приём"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors/foto",
                        verbose_name="Фотография врача",
                    ),
                ),
                (
                    "med_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meddata.medbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.CreateModel(
            name="MedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование услуги"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание услуги"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена услуги")),
                (
                    "med_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meddata.medbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
