# Generated by Django 5.1.2 on 2024-10-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование услуги"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание услуги"
                    ),
                ),
                (
                    "med_branch",
                    models.TextField(
                        blank=True, null=True, verbose_name="Направление мед.услуги"
                    ),
                ),
                (
                    "doctors",
                    models.TextField(
                        blank=True, null=True, verbose_name="Список врачей"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена услуги")),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
