# Generated by Django 5.1.2 on 2024-10-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100, verbose_name="фамилия")),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                (
                    "patronymic",
                    models.CharField(max_length=100, verbose_name="отчество"),
                ),
                (
                    "biography",
                    models.TextField(blank=True, null=True, verbose_name="биография"),
                ),
                (
                    "med_branch",
                    models.TextField(
                        blank=True, null=True, verbose_name="Направление мед"
                    ),
                ),
                (
                    "appointments",
                    models.TextField(
                        blank=True, null=True, verbose_name="записи на приём"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors/foto",
                        verbose_name="Фотография врача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
    ]
