# Generated by Django 5.1.2 on 2024-10-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddata", "0005_alter_appointment_options_alter_doctor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field=540,
                null=True,
                upload_to="doctors/foto",
                verbose_name="Фотография врача",
                width_field=540,
            ),
        ),
    ]
