# Generated by Django 5.1.2 on 2024-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddata", "0006_alter_doctor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="doctors/foto",
                verbose_name="Фотография врача",
            ),
        ),
    ]
